### ISSUE TITLE
不使用回调函数获取数据库内容的方法是怎样的？

### ISSUE THREAD

**Issue by Ethan-zhengyw** [natsu12/Activitee#33]
我之前一直在回调函数里使用需要的信息，在只需要一种信息的时候没有问题，但是现在有要这样来两次
比如：先获取用户信息，这样在回调函数里就能用详细的用户信息，然后我还需要Tag的详细数据，又要使用多一次，这样之前获取的User的信息就不能用了。求解决方法

**Comment by natsu12** [comment]
为什么之前获取的User的信息就不能用了？不是可以在回调函数中嵌套使用find或者findOne吗？
![2015-06-05 5 47 27](https://cloud.githubusercontent.com/assets/7494889/8003464/3d917696-0baa-11e5-818d-8385e4989fef.png)
例如在详情页中，我首先要找到这个活动，然后要找到这个活动中的评论。

**Comment by Ethan-zhengyw** [comment]
奇怪，我刚刚在第二层里log不出拿到的user。我再看看``

**Comment by Ethan-zhengyw** [comment]
```
User.find-by-id id, (err, user)!->
      console.log err if err

    # 活取所有可选的tags
    Tag.find {}, (err, tags)->
      console.log 'query available tags failed!' if err

      tagNames = [tag.name for tag in tags]
      console.log tagNames
      console.log user
```

我这里这样用对是不是哪里出了问题，log user出现就undefine了

**Comment by Ethan-zhengyw** [comment]
呀````你是对的，我前面的缩进影响到了。
