### ISSUE TITLE
大家进入活动详情页的时候正常吗？

### ISSUE THREAD

**Issue by natsu12** [natsu12/Activitee#52]
今天merge了几个人的代码之后，进入活动详情页程序就崩了，看后台报错是什么id是undefined。然后我log一下从路由请求的参数获取的id（/controllers/page/detail.ls），如下：
![0185214a-40b3-47b1-a7dc-24d8c1ec3d4c](https://cloud.githubusercontent.com/assets/7494889/8113170/e0e7bc08-109e-11e5-80f6-20946a6a02a5.png)

发现竟然这个controller竟然调用了两次（发生了两次请求），第一次是正常的，能获取到请求的id：
![faf180c0-11d2-4b78-922c-f49d36137334](https://cloud.githubusercontent.com/assets/7494889/8113212/2230d032-109f-11e5-95bb-64d3396595e3.png)

然后它下面又log了一次（证明调用了两次controller），这次是undefined，然后程序就崩了：
![46919e5f-6a82-4bc9-9824-2c517415f9ee](https://cloud.githubusercontent.com/assets/7494889/8113282/8251e956-109f-11e5-8f6c-1da863a9c600.png)
![082d183c-63b3-4f41-900c-41adbc1ef089](https://cloud.githubusercontent.com/assets/7494889/8113285/89a20b6e-109f-11e5-9efc-1c2d7f5d1b45.png)

**Comment by ghostbody** [comment]
为什么会请求两次？没搞懂。。。我好像没有这个问题=_=

**Comment by Ethan-zhengyw** [comment]
undefine的话是不是没有查询到相应的活动，直接用一个空的对象去渲染页面了

**Comment by ghostbody** [comment]
下面还有一个cast error应该是这个问题。但是，即使调用两次controler 也应该能够渲染到那个活动哇，不应该出现一个空对象。而且也不知道为什么调用两次。

**Comment by natsu12** [comment]
是发了一次评论之后就会这样，没有查询到相应的活动归根到底是因为从路由的参数那里获取的req.param.id是undefined，cast error也是同样的道理（归根结底是因为req.param.id是undefined，所以不能把它转化成ObjectId的类型）
